2020-05-18 20:37:45,866 ERROR: Exception on /user/sovannarith [GET] [in D:\learning\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\learning\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\learning\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\learning\microblog\app\routes.py", line 67, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2020-05-18 20:37:47,753 ERROR: Exception on /index [GET] [in D:\learning\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\learning\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\learning\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\learning\microblog\app\routes.py", line 14, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-05-18 20:37:52,179 ERROR: Exception on /index [GET] [in D:\learning\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\learning\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\learning\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\learning\microblog\app\routes.py", line 14, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-05-18 20:37:52,866 ERROR: Exception on /index [GET] [in D:\learning\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\learning\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\learning\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\learning\microblog\app\routes.py", line 14, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-05-18 20:37:53,266 ERROR: Exception on /index [GET] [in D:\learning\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\learning\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\learning\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\learning\microblog\app\routes.py", line 14, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-05-18 20:40:59,869 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:47]
2020-05-18 20:41:09,021 ERROR: Exception on /explore [GET] [in D:\learning\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\learning\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\learning\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\learning\microblog\app\routes.py", line 136, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "D:\learning\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "D:\learning\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\learning\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\learning\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "D:\learning\microblog\app\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
